/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Владимир
 */
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
import java.io.File;
import java.io.IOException;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.beans.*;
import java.util.Random;
import java.util.Vector;


public class mocsparserUI extends javax.swing.JFrame{

    private TaskParsingEdx task;
    /**
     * Creates new form mocsparserUI
     */
    public mocsparserUI() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Запустить");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextArea1PropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jCheckBox1.setText("jCheckBox1");

        jCheckBox2.setText("jCheckBox2");

        jCheckBox3.setText("jCheckBox3");

        jCheckBox4.setText("jCheckBox4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jProgressBar1.setToolTipText("");
        jProgressBar1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jProgressBar1PropertyChange(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(38, 38, 38)
                                .addComponent(jButton2))
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 573, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(9, 9, 9)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.getAccessibleContext().setAccessibleName("run_button");
        jButton1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    class TaskParsingEdx extends SwingWorker<Void, Void> {
        /*
         * Main task. Executed in background thread.
         */
        @Override
        public Void doInBackground() {
            int progress = 0;
            float fProgress = 0;
            Document doc = null;
            Document doc_courses = null;
            Element next;
            Vector links = new Vector(); 
            try {
                doc = Jsoup.connect("https://www.edx.org/course-list").get();
            } catch (IOException e) {
                jTextArea1.append("!!!!Exception!!!! - " + e.toString());
            }
            boolean check1 = doc.select("li[class=pager-next odd]").isEmpty();
            boolean check2 = doc.select("li[class=pager-next even]").isEmpty();
            Elements course_titles = doc.select("h2[class=title course-title]");
            for(Element course_title : course_titles)
            {
                String s = course_title.select("a").first().attr("href");
                jTextArea1.append(s + "\n");
                links.add(s);
            }

            while (!doc.select("li[class=pager-next odd]").isEmpty())
            {

               // check1 = doc.select("li[class=pager-next odd]").isEmpty();
              //  jTextArea1.append("check1 = " + Boolean.toString(check1) + "\n");
               // check2 = doc.select("li[class=pager-next even]").isEmpty();
              //  jTextArea1.append("check2 = " + Boolean.toString(check2) + "\n");
               // if (check1)
               //     next = doc.select("li[class=pager-next even]").first();
               // else
                next = doc.select("li[class=pager-next odd]").first();
                String s = next.select("a").first().attr("href");
                doc.empty();
                try {
                    doc = Jsoup.connect("https://www.edx.org" + s).get();
                } catch (IOException e) {
                    jTextArea1.append("!!!!Exception!!!! - " + e.toString());
                }
                course_titles = doc.select("h2[class=title course-title]");
                for(Element course_title : course_titles)
                {
                    String tmp = course_title.select("a").first().attr("href");
                    jTextArea1.append(tmp + "\n");
                    links.add(tmp);
                }
                
                for (Object link: links)
                {
                    if (doc_courses!=null)
                        doc_courses.empty();
                    try {
                        jTextArea1.append("Connecting = " + link.toString());
                        doc_courses = Jsoup.connect(link.toString()).get();
                    } catch (IOException e) {
                        jTextArea1.append("!!!!Exception!!!! - " + e.toString());
                    }
                    Element course_info = doc_courses.select("div[class=copy-detail course-detail-info views-fieldset]").first();
                    Element school = course_info.select("div[class=course-detail-school item]").first();
                    String schoolname = school.select("a").first().html();
                    String start = "";
                    String length = "";
                    String estimate = "";
                    String about = "";
                    if (!course_info.select("div[class=course-detail-start item]").isEmpty())
                        start = course_info.select("div[class=course-detail-start item]").first().html();
                    if (!course_info.select("div[class=course-detail-length item]").isEmpty())
                        length = course_info.select("div[class=course-detail-length item]").first().html();
                    if (!course_info.select("div[class=course-detail-effort item]").isEmpty())
                        estimate = course_info.select("div[class=course-detail-effort item]").first().html();
                    about = doc_courses.select("div[class=course-section course-detail-about]").first().html();
                    jTextArea1.append(schoolname + "\n" + start + "\n" + length + "\n" + estimate + "\n" + about + "\n");
                }
            }
            
           /* jTextArea1.append("courseNum = ");
            int courseNum = links.toArray().length;
            jTextArea1.append("courseNum = " + Integer.toString(courseNum));
            float step = 100/courseNum;
            for (Object link: links)
            {
                doc.empty();
                try {
                    jTextArea1.append("Connecting = " + link.toString());
                    doc = Jsoup.connect(link.toString()).get();
                } catch (IOException e) {
                    jTextArea1.append("!!!!Exception!!!! - " + e.toString());
                }
                Element course_info = doc.select("div[class=copy-detail course-detail-info views-fieldset]").first();
                Element school = course_info.select("div[class=course-detail-school item]").first();
                String schoolname = school.select("a").first().html();
                String start = course_info.select("div[class=course-detail-start item]").first().html();
                String length = course_info.select("div[class=course-detail-length item]").first().html();
                String estimate = course_info.select("div[class=course-detail-effort item]").first().html();
                String about = doc.select("div[class=course-section course-detail-about]").first().html();
                jTextArea1.append(schoolname + "\n" + start + "\n" + length + "\n" + estimate + "\n" + about + "\n");
                fProgress += step;
                progress = Math.round(fProgress); 
                jProgressBar1.firePropertyChange("progress",jProgressBar1.getValue(),progress);
            }*/
            
            return null;
        }
        

        /*
         * Executed in event dispatching thread
         */
        @Override
        public void done() {
            //Toolkit.getDefaultToolkit().beep();
            jButton2.setEnabled(true);
            //setCursor(null); //turn off the wait cursor
            jTextArea1.append("Done!\n");
        }
    }
    
    class TaskParsingMyeducationkey extends SwingWorker<Void, Void> {
        /*
         * Main task. Executed in background thread.
         */
        @Override
        public Void doInBackground() {
            int progress = 0;
            float fProgress = 0;
            //Initialize progress property.
            setProgress(0);
            Document doc = null;
            Document courses_doc = null;
            try {
                doc = Jsoup.connect("http://www.myeducationkey.com/").get();
            } catch (IOException e) {
                jTextArea1.append("!!!!Exception!!!! - " + e.toString());
            }
            Element university_education = doc.select("#subject-base").first(); 
            Elements specs = university_education.select("a.box-title");
            int specNum = specs.toArray().length;
            float step = 100/specNum;
            int departmentNum = -1;
            float departmentStep;
            int coursesNum = -1;
            float coursesStep;
            //jTextArea1.append("step="+Float.toString(step));
            for(Element spec : specs)
            {
                //jTextArea1.append(spec.html() + " - " + spec.attr("href").toString());
                doc.empty();
                try {
                    doc = Jsoup.connect(spec.attr("href")).get();
                    //jTextArea1.append("Parsing spec \n");
                } catch (IOException e) {
                    jTextArea1.append("!!!!Exception!!!! - " + e.toString());
                }
                String spec_title = doc.select("a.title").first().html().toString();
                Elements departments = doc.select("a.department-img-title");
                
                departmentNum = departments.toArray().length;
                departmentStep =  step/departmentNum;
                //jTextArea1.append("departmentStep="+Float.toString(departmentStep));
                for (Element department: departments)
                {
                    //jTextArea1.append("Parsing departments \n");
                    if (courses_doc!=null)
                        courses_doc.empty();

                    try {
                        courses_doc = Jsoup.connect(department.attr("href")).get();
                    } catch (IOException e) {
                        jTextArea1.append("!!!!Exception!!!! - " + e.toString());
                    }
                    Elements courses = courses_doc.select("div#main-sub-dpm-base");
                    coursesNum = courses.toArray().length;
                    coursesStep = departmentStep/coursesNum;
                    //jTextArea1.append("coursesStep="+Float.toString(coursesStep));
                    for (Element course: courses)
                    {
                        //jTextArea1.append("Parsing courses \n");
                        String course_from = course.select("div.sub-dpm-sub-title").first().html().toString();
                        Element course_title = course.select("a.sub-dpm-title").first();
                        courses_doc.empty();
                        try {
                            courses_doc = Jsoup.connect(course_title.attr("href")).get();
                        } catch (IOException e) {
                            jTextArea1.append("!!!!Exception!!!! - " + e.toString());

                            continue;
                        } 
                       // if (courses_doc->find('div[class=title]',0)->text()!='Error 404 - Not Found')   //hack
                        //{
                        String course_desc = courses_doc.select("div.text").first().html().toString().replaceAll("\r\n", " ");
                      //  jTextArea1.append("{ \n");

                        
                        jTextArea1.append("    \"speciality\": \"" + spec_title + "\"," + " \n");
                        jTextArea1.append("    \"department\": \"" + department.html().toString() + "\"," + " \n");
                        jTextArea1.append("    \"title\": \"" + course_title.html().toString() + "\"," + " \n");
                        jTextArea1.append("    \"from\": \"" + course_from + "\"," + " \n");
                        jTextArea1.append("    \"description\": \"" + course_desc.trim() + "\"" + " \n");
                        jTextArea1.append("}," + " \n");
                      
                        fProgress += coursesStep;
                        progress = Math.round(fProgress); 
                        jProgressBar1.firePropertyChange("progress",jProgressBar1.getValue(),progress);
                     // }
                    }
                }
            }
            progress = 100; 
            jProgressBar1.firePropertyChange("progress",jProgressBar1.getValue(),progress);
            return null;
        }
        

        /*
         * Executed in event dispatching thread
         */
        @Override
        public void done() {
            Toolkit.getDefaultToolkit().beep();
            jButton2.setEnabled(true);
            setCursor(null); //turn off the wait cursor
            jTextArea1.append("Done!\n");
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jCheckBox1.isSelected())
        {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jProgressBar1.setStringPainted(true);
        task = new TaskParsingEdx();
        task.execute();
        jButton2.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jProgressBar1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jProgressBar1PropertyChange
        if ("progress" == evt.getPropertyName()) {
            int progress = (Integer) evt.getNewValue();
            jProgressBar1.setValue(progress);
           // jTextArea1.append(String.format(
            //        "Completed %d%% of task.\n", progress));
        } 
    }//GEN-LAST:event_jProgressBar1PropertyChange

    private void jTextArea1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextArea1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mocsparserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mocsparserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mocsparserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mocsparserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mocsparserUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
